// The value tables are the one place the studio editor can be silently wrong:
// a slider position is not the value the engine wants, and sending the raw
// position would mistune every synth without throwing anything. These tests
// check the mapping against the standalone pages' own transforms.

import { describe, it, expect } from 'vitest'
import { readFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'
import { engineValue, sliderPosition, formatValue, type ParamSpec } from '../src/lib/synth-data.ts'

const BANK = (kind: string) => resolve(__dirname, `../public/synths/${kind}.json`)

/** Generated by predev/prebuild; skip rather than fail if it has not run. */
const generated = existsSync(BANK('va'))
const load = (kind: string) =>
  JSON.parse(readFileSync(BANK(kind), 'utf8')) as { params: ParamSpec[] }

describe('value mapping', () => {
  it('is the identity when a control has no transform', () => {
    const spec: ParamSpec = { param: 'x', label: 'X', group: 'g', type: 'range', min: 0, max: 1, step: 0.01 }
    expect(engineValue(spec, 0.42)).toBe(0.42)
    expect(sliderPosition(spec, 0.42)).toBe(0.42)
  })

  it('maps through the table when there is one', () => {
    const spec: ParamSpec = {
      param: 'x', label: 'X', group: 'g', type: 'range',
      min: 0, max: 1, step: 0.5, values: [10, 100, 1000],
    }
    expect(engineValue(spec, 0)).toBe(10)
    expect(engineValue(spec, 0.5)).toBe(100)
    expect(engineValue(spec, 1)).toBe(1000)
    expect(sliderPosition(spec, 1000)).toBe(1)
  })

  it('clamps positions outside the table', () => {
    const spec: ParamSpec = {
      param: 'x', label: 'X', group: 'g', type: 'range',
      min: 0, max: 1, step: 0.5, values: [10, 100, 1000],
    }
    expect(engineValue(spec, -5)).toBe(10)
    expect(engineValue(spec, 99)).toBe(1000)
  })

  it('formats with the standalone page\'s suffix and precision', () => {
    const hz: ParamSpec = {
      param: 'filterCutoff', label: 'Cutoff', group: 'Filter', type: 'range',
      suffix: 'Hz', decimals: 0,
    }
    expect(formatValue(hz, 7096.4)).toBe('7096Hz')
    const plain: ParamSpec = { param: 'reso', label: 'Reso', group: 'Filter', type: 'range', step: 0.01 }
    expect(formatValue(plain, 0.5)).toBe('0.50')
  })
})

describe.skipIf(!generated)('extracted banks', () => {
  it("reproduces VA's logarithmic cutoff transform", () => {
    const spec = load('va').params.find(p => p.param === 'filterCutoff')
    expect(spec?.values).toBeDefined()
    // The page's own mapping: 0 → 20 Hz, 1 → 20 kHz, log in between.
    const truth = (v: number) => 20 * Math.pow(1000, v)
    for (let i = 0; i <= 100; i++) {
      const pos = i / 100
      expect(engineValue(spec!, pos)).toBeCloseTo(truth(pos), 4)
    }
  })

  // Position cannot round-trip in general: SID quantises with
  // Math.round(v * 255), so 1001 slider positions collapse onto 256 values.
  // What must hold is that the *sound* survives the round trip.
  it('round-trips the engine value from every slider position', () => {
    for (const kind of ['va', 'ws', 'sid', 'fm', 'pm']) {
      for (const spec of load(kind).params) {
        if (!spec.values) continue
        const step = spec.step || 1
        for (let i = 0; i < spec.values.length; i++) {
          const pos = (spec.min ?? 0) + i * step
          const engine = engineValue(spec, pos)
          expect(engineValue(spec, sliderPosition(spec, engine))).toBe(engine)
        }
      }
    }
  })

  it('maps positions monotonically, so a slider never runs backwards', () => {
    for (const kind of ['va', 'ws', 'sid', 'fm', 'pm']) {
      for (const spec of load(kind).params) {
        if (!spec.values || spec.values.length < 2) continue
        const rising = spec.values[spec.values.length - 1]! >= spec.values[0]!
        for (let i = 1; i < spec.values.length; i++) {
          const a = spec.values[i - 1]!
          const b = spec.values[i]!
          expect(rising ? b >= a : b <= a, `${kind}:${spec.param} at ${i}`).toBe(true)
        }
      }
    }
  })

  it('gives every control a name, a label and a group', () => {
    for (const kind of ['va', 'ws', 'sid', 'fm', 'pm', 'drum']) {
      for (const spec of load(kind).params) {
        expect(spec.param, `${kind} param name`).toBeTruthy()
        expect(spec.label, `${kind}:${spec.param} label`).toBeTruthy()
        expect(spec.group, `${kind}:${spec.param} group`).toBeTruthy()
        if (spec.type === 'select') expect(spec.options?.length).toBeGreaterThan(0)
      }
    }
  })

  it('keeps the drum bank as patterns and the rest as sounds', () => {
    const drum = JSON.parse(readFileSync(BANK('drum'), 'utf8')) as {
      presets: { name: string; pattern?: number[][]; params?: object }[]
    }
    expect(drum.presets.length).toBeGreaterThan(0)
    for (const p of drum.presets) expect(p.pattern).toBeDefined()

    const va = JSON.parse(readFileSync(BANK('va'), 'utf8')) as {
      presets: { name: string; params?: Record<string, unknown> }[]
    }
    for (const p of va.presets) expect(Object.keys(p.params ?? {}).length).toBeGreaterThan(0)
  })
})
