// Code generated by protoc-gen-go. DO NOT EDIT.
// source: images.proto

package images

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Image struct {
	Width                int32    `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Imgdata              []byte   `protobuf:"bytes,4,opt,name=imgdata,proto3" json:"imgdata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_images_8a8d5d600b1ea8b3, []int{0}
}
func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (dst *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(dst, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Image) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Image) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Image) GetImgdata() []byte {
	if m != nil {
		return m.Imgdata
	}
	return nil
}

type ObjectDetection struct {
	Xstart               int32    `protobuf:"varint,1,opt,name=xstart,proto3" json:"xstart,omitempty"`
	Xend                 int32    `protobuf:"varint,2,opt,name=xend,proto3" json:"xend,omitempty"`
	Ystart               int32    `protobuf:"varint,3,opt,name=ystart,proto3" json:"ystart,omitempty"`
	Yend                 int32    `protobuf:"varint,4,opt,name=yend,proto3" json:"yend,omitempty"`
	Likelihood           float32  `protobuf:"fixed32,5,opt,name=likelihood,proto3" json:"likelihood,omitempty"`
	Type                 int32    `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObjectDetection) Reset()         { *m = ObjectDetection{} }
func (m *ObjectDetection) String() string { return proto.CompactTextString(m) }
func (*ObjectDetection) ProtoMessage()    {}
func (*ObjectDetection) Descriptor() ([]byte, []int) {
	return fileDescriptor_images_8a8d5d600b1ea8b3, []int{1}
}
func (m *ObjectDetection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectDetection.Unmarshal(m, b)
}
func (m *ObjectDetection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectDetection.Marshal(b, m, deterministic)
}
func (dst *ObjectDetection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectDetection.Merge(dst, src)
}
func (m *ObjectDetection) XXX_Size() int {
	return xxx_messageInfo_ObjectDetection.Size(m)
}
func (m *ObjectDetection) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectDetection.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectDetection proto.InternalMessageInfo

func (m *ObjectDetection) GetXstart() int32 {
	if m != nil {
		return m.Xstart
	}
	return 0
}

func (m *ObjectDetection) GetXend() int32 {
	if m != nil {
		return m.Xend
	}
	return 0
}

func (m *ObjectDetection) GetYstart() int32 {
	if m != nil {
		return m.Ystart
	}
	return 0
}

func (m *ObjectDetection) GetYend() int32 {
	if m != nil {
		return m.Yend
	}
	return 0
}

func (m *ObjectDetection) GetLikelihood() float32 {
	if m != nil {
		return m.Likelihood
	}
	return 0
}

func (m *ObjectDetection) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func init() {
	proto.RegisterType((*Image)(nil), "images.Image")
	proto.RegisterType((*ObjectDetection)(nil), "images.ObjectDetection")
}

func init() { proto.RegisterFile("images.proto", fileDescriptor_images_8a8d5d600b1ea8b3) }

var fileDescriptor_images_8a8d5d600b1ea8b3 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x40, 0xc9, 0x76, 0x77, 0xc5, 0xa1, 0x28, 0x0c, 0x22, 0x39, 0x49, 0xe8, 0x29, 0x27, 0x2f,
	0xfe, 0x82, 0x17, 0x4f, 0x42, 0x7e, 0x40, 0xd2, 0x66, 0xd8, 0x8c, 0xb6, 0x4d, 0x69, 0x07, 0xdc,
	0x7c, 0x8c, 0xff, 0x2a, 0xd9, 0x44, 0xe9, 0xed, 0xbd, 0xe1, 0x4d, 0x06, 0x02, 0x6b, 0x3e, 0xf8,
	0x89, 0x2e, 0xcf, 0xa7, 0x73, 0x92, 0x84, 0x63, 0xb5, 0xcd, 0x07, 0x0c, 0x6f, 0x85, 0xf0, 0x01,
	0x86, 0x6f, 0x0e, 0x12, 0xb5, 0x32, 0xca, 0x0e, 0xae, 0x0a, 0x3e, 0xc2, 0x18, 0x89, 0xa7, 0x28,
	0xba, 0x5b, 0xc6, 0xcd, 0xf0, 0x0e, 0x3a, 0x0e, 0x7a, 0x65, 0x94, 0xbd, 0x75, 0x1d, 0x07, 0xd4,
	0x70, 0xc3, 0x87, 0x29, 0x78, 0xf1, 0xba, 0x37, 0xca, 0xae, 0xdd, 0x9f, 0x6e, 0x7e, 0x14, 0xdc,
	0xbf, 0x6f, 0x3f, 0x69, 0x27, 0xaf, 0x24, 0xb4, 0x13, 0x4e, 0xc7, 0xf2, 0xea, 0x7c, 0x11, 0x7f,
	0x96, 0x76, 0xac, 0x19, 0x22, 0xf4, 0x33, 0x1d, 0x43, 0xbb, 0xb5, 0x70, 0x69, 0x73, 0x6d, 0x57,
	0xb5, 0xcd, 0xff, 0x6d, 0x2e, 0x6d, 0x5f, 0xdb, 0xc2, 0xf8, 0x04, 0xb0, 0xe7, 0x2f, 0xda, 0x73,
	0x4c, 0x29, 0xe8, 0xc1, 0x28, 0xdb, 0xb9, 0xab, 0x49, 0xd9, 0x91, 0x7c, 0x22, 0x3d, 0xd6, 0x9d,
	0xc2, 0xdb, 0x71, 0xf9, 0x8f, 0x97, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa8, 0xd8, 0xb0, 0x57,
	0x1f, 0x01, 0x00, 0x00,
}
