# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pipeconfig.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pipeconfig.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10pipeconfig.proto\x1a\x19google/protobuf/any.proto\"7\n\x0fInputStreamInfo\x12\x11\n\ttag_index\x18\x01 \x01(\t\x12\x11\n\tback_edge\x18\x02 \x01(\x08\"\xbf\x02\n\x15\x43\x61lculatorGraphConfig\x12)\n\x04node\x18\x01 \x03(\x0b\x32\x1b.CalculatorGraphConfig.Node\x12\x14\n\x0cinput_stream\x18\n \x03(\t\x12\x15\n\routput_stream\x18\x0f \x03(\t\x12\x0f\n\x07package\x18\x13 \x01(\t\x12\x0c\n\x04type\x18\x14 \x01(\t\x1a\xae\x01\n\x04Node\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\ncalculator\x18\x02 \x01(\t\x12\x14\n\x0cinput_stream\x18\x03 \x03(\t\x12\x15\n\routput_stream\x18\x04 \x03(\t\x12*\n\x0cnode_options\x18\x08 \x03(\x0b\x32\x14.google.protobuf.Any\x12+\n\x11input_stream_info\x18\r \x03(\x0b\x32\x10.InputStreamInfob\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_INPUTSTREAMINFO = _descriptor.Descriptor(
  name='InputStreamInfo',
  full_name='InputStreamInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag_index', full_name='InputStreamInfo.tag_index', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='back_edge', full_name='InputStreamInfo.back_edge', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=102,
)


_CALCULATORGRAPHCONFIG_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='CalculatorGraphConfig.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='CalculatorGraphConfig.Node.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='calculator', full_name='CalculatorGraphConfig.Node.calculator', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_stream', full_name='CalculatorGraphConfig.Node.input_stream', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_stream', full_name='CalculatorGraphConfig.Node.output_stream', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node_options', full_name='CalculatorGraphConfig.Node.node_options', index=4,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_stream_info', full_name='CalculatorGraphConfig.Node.input_stream_info', index=5,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=424,
)

_CALCULATORGRAPHCONFIG = _descriptor.Descriptor(
  name='CalculatorGraphConfig',
  full_name='CalculatorGraphConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node', full_name='CalculatorGraphConfig.node', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_stream', full_name='CalculatorGraphConfig.input_stream', index=1,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_stream', full_name='CalculatorGraphConfig.output_stream', index=2,
      number=15, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='package', full_name='CalculatorGraphConfig.package', index=3,
      number=19, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='CalculatorGraphConfig.type', index=4,
      number=20, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CALCULATORGRAPHCONFIG_NODE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=424,
)

_CALCULATORGRAPHCONFIG_NODE.fields_by_name['node_options'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_CALCULATORGRAPHCONFIG_NODE.fields_by_name['input_stream_info'].message_type = _INPUTSTREAMINFO
_CALCULATORGRAPHCONFIG_NODE.containing_type = _CALCULATORGRAPHCONFIG
_CALCULATORGRAPHCONFIG.fields_by_name['node'].message_type = _CALCULATORGRAPHCONFIG_NODE
DESCRIPTOR.message_types_by_name['InputStreamInfo'] = _INPUTSTREAMINFO
DESCRIPTOR.message_types_by_name['CalculatorGraphConfig'] = _CALCULATORGRAPHCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputStreamInfo = _reflection.GeneratedProtocolMessageType('InputStreamInfo', (_message.Message,), {
  'DESCRIPTOR' : _INPUTSTREAMINFO,
  '__module__' : 'pipeconfig_pb2'
  # @@protoc_insertion_point(class_scope:InputStreamInfo)
  })
_sym_db.RegisterMessage(InputStreamInfo)

CalculatorGraphConfig = _reflection.GeneratedProtocolMessageType('CalculatorGraphConfig', (_message.Message,), {

  'Node' : _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), {
    'DESCRIPTOR' : _CALCULATORGRAPHCONFIG_NODE,
    '__module__' : 'pipeconfig_pb2'
    # @@protoc_insertion_point(class_scope:CalculatorGraphConfig.Node)
    })
  ,
  'DESCRIPTOR' : _CALCULATORGRAPHCONFIG,
  '__module__' : 'pipeconfig_pb2'
  # @@protoc_insertion_point(class_scope:CalculatorGraphConfig)
  })
_sym_db.RegisterMessage(CalculatorGraphConfig)
_sym_db.RegisterMessage(CalculatorGraphConfig.Node)


# @@protoc_insertion_point(module_scope)
