[project]
authors = ["Joakim Eriksson <joakim.eriksson@ri.se>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "js-postit"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.2,<3.14"
numpy = ">=2.2.3,<3"
pyyaml = ">=6.0.2,<7"
pillow = ">=11.1.0,<12"
pip = ">=25.0.1,<26"
