// PolyBLEP-corrected oscillators (saw + square+PWM + triangle).
// Reference: Välimäki & Huovilainen, "Antialiasing Oscillators in Subtractive Synthesis".
//
// All oscillators expose a stateful `next(dt)` returning the next sample in
// roughly [-1, 1]. dt = freq / sampleRate; clamp the caller side to keep the
// BLEP correction window valid (roughly dt < 0.4).

// PolyBLEP residual at the discontinuity of a saw wrapping 1 → 0.
export function polyBlep(t: number, dt: number): number {
  if (t < dt) {
    const x = t / dt
    return x + x - x * x - 1
  }
  if (t > 1 - dt) {
    const x = (t - 1) / dt
    return x * x + x + x + 1
  }
  return 0
}

// Hard-sync helper: returns true if the oscillator wrapped during the
// last `next()` call. Caller can react by phase-resetting a slave osc.
export interface PhaseOsc {
  phase: number
  wrapped: boolean
  reset(phase?: number): void
  syncTo(phase: number): void
}

export class PolyBlepSaw implements PhaseOsc {
  phase = 0
  wrapped = false

  reset(phase = 0): void {
    this.phase = phase
    this.wrapped = false
  }

  // Soft-sync: jump to a given phase mid-cycle without affecting the BLEP
  // correction state — used by hard sync from a master oscillator.
  syncTo(phase: number): void {
    this.phase = phase
  }

  next(dt: number): number {
    let saw = 2 * this.phase - 1
    saw -= polyBlep(this.phase, dt)
    this.phase += dt
    if (this.phase >= 1) {
      this.phase -= 1
      this.wrapped = true
    } else {
      this.wrapped = false
    }
    return saw
  }
}

// Square / pulse with variable PWM. Implemented as two sub-saws offset by
// `pwm` and subtracted (classic trick); BLEPs apply at both discontinuities.
// `pwm` is duty cycle in [0.05, 0.95] — caller clamps.
export class PolyBlepSquare implements PhaseOsc {
  phase = 0
  wrapped = false

  reset(phase = 0): void {
    this.phase = phase
    this.wrapped = false
  }

  syncTo(phase: number): void {
    this.phase = phase
  }

  next(dt: number, pwm: number): number {
    // Two virtual saws: one starting at 0, one starting at -pwm (i.e. ahead).
    // Naive square = sign(0.5 - phase shifted by pwm).
    const phase2 = this.phase + (1 - pwm)
    const ph2 = phase2 >= 1 ? phase2 - 1 : phase2
    let s = this.phase < pwm ? 1 : -1
    s += polyBlep(this.phase, dt)
    s -= polyBlep(ph2, dt)
    this.phase += dt
    if (this.phase >= 1) {
      this.phase -= 1
      this.wrapped = true
    } else {
      this.wrapped = false
    }
    return s
  }
}

// Triangle, generated by leaky-integrating a band-limited square. The leaky
// pole removes DC and prevents drift; the integrator is normalized so peak
// amplitude stays near ±1 across the audible range.
export class PolyBlepTriangle implements PhaseOsc {
  phase = 0
  wrapped = false
  private z = 0
  private readonly square = new PolyBlepSquare()

  reset(phase = 0): void {
    this.phase = phase
    this.wrapped = false
    this.z = 0
    this.square.reset(phase)
  }

  syncTo(phase: number): void {
    this.phase = phase
    this.square.syncTo(phase)
    // Don't reset z — keeps integrator continuous across the sync.
  }

  next(dt: number): number {
    const sq = this.square.next(dt, 0.5)
    // Leaky integrator: y[n] = leak * y[n-1] + g * x[n]
    // Normalize so peak ≈ 1 at typical pitches.
    const g = 4 * dt
    const leak = 1 - 0.001
    this.z = leak * this.z + g * sq
    this.phase = this.square.phase
    this.wrapped = this.square.wrapped
    return this.z
  }
}

// Sine. Used for "pure" waveforms in some patches (pan flutes, tremolo
// piano). Trivially aliasing-free.
export class SineOsc implements PhaseOsc {
  phase = 0
  wrapped = false

  reset(phase = 0): void {
    this.phase = phase
    this.wrapped = false
  }

  syncTo(phase: number): void {
    this.phase = phase
  }

  next(dt: number): number {
    const out = Math.sin(this.phase * 2 * Math.PI)
    this.phase += dt
    if (this.phase >= 1) {
      this.phase -= 1
      this.wrapped = true
    } else {
      this.wrapped = false
    }
    return out
  }
}
