export { Synth } from './synth.ts'
export type { SynthOptions } from './synth.ts'
export { VoicePool } from './voice.ts'
export type { VoiceSlot } from './voice.ts'
export { factoryDefault } from './presets/default.ts'
export { default as factoryBank, PRESETS, MEMORIES } from './presets/factory.ts'
export type { FactorySlot, MemorySlot } from './presets/factory.ts'
export type * from './patch.ts'
export { mergeDeep } from './patch.ts'
export type { DeepPartial } from './patch.ts'
