#
# MorphOS makefile
#

CFLAGS=`sdl-config --cflags`
PREFIX=../morphos/
SUFFIX=
LIBS=`sdl-config --libs`

include makefile.common

dist: ../readme.txt
	rx /morphos/ReadMe2Guide <$? >../morphos/goattracker.guide goattracker.guide 2.75
